use_frameworks!

platform :ios, '9.0'

target 'myPublicPod_Example' do
  pod 'myPublicPod', :path => '../'

  target 'myPublicPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
